import type { Product } from "@/types/product-types";

export const MOCK_PRODUCTS: Product[] = [
  {
    id: "1",
    businessId: "P001",
    name: "经典白色圆领T恤 纯棉透气",
    description: "100%纯棉面料，柔软透气，经典百搭",
    price: "59.00",
    stock: 200,
    imageUrl: "https://picsum.photos/seed/tshirt/400/400",
    category: "服饰",
    status: "active",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "2",
    businessId: "P002",
    name: "无线蓝牙降噪耳机 HIFI音质",
    description: "主动降噪，40小时续航，高清通话",
    price: "299.00",
    stock: 80,
    imageUrl: "https://picsum.photos/seed/headphone/400/400",
    category: "数码",
    status: "active",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "3",
    businessId: "P003",
    name: "手工牛轧糖礼盒装 多口味混合",
    description: "精选原料，手工制作，送礼佳品",
    price: "39.90",
    stock: 500,
    imageUrl: "https://picsum.photos/seed/candy/400/400",
    category: "美食",
    status: "active",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "4",
    businessId: "P004",
    name: "便携式迷你充电宝 10000mAh",
    description: "轻薄便携，快充协议，双口输出",
    price: "89.00",
    stock: 150,
    imageUrl: "https://picsum.photos/seed/powerbank/400/400",
    category: "数码",
    status: "active",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "5",
    businessId: "P005",
    name: "保湿补水面膜套装 28片装",
    description: "玻尿酸精华，深层补水，温和不刺激",
    price: "68.00",
    stock: 300,
    imageUrl: "https://picsum.photos/seed/skincare/400/400",
    category: "美妆",
    status: "active",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "6",
    businessId: "P006",
    name: "北欧简约台灯 LED护眼",
    description: "三档调光，USB充电，卧室书桌两用",
    price: "128.00",
    stock: 60,
    imageUrl: "https://picsum.photos/seed/lamp/400/400",
    category: "家居",
    status: "active",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "7",
    businessId: "P007",
    name: "双肩背包男女通用 大容量防水",
    description: "防泼水面料，多隔层收纳，减压背带",
    price: "149.00",
    stock: 120,
    imageUrl: "https://picsum.photos/seed/backpack/400/400",
    category: "服饰",
    status: "active",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "8",
    businessId: "P008",
    name: "精选挂耳咖啡 意式浓缩 20包",
    description: "新鲜烘焙，独立包装，随时享用",
    price: "49.90",
    stock: 400,
    imageUrl: "https://picsum.photos/seed/coffee/400/400",
    category: "美食",
    status: "active",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "9",
    businessId: "P009",
    name: "智能手表运动版 心率血氧监测",
    description: "全天候健康监测，14天超长续航",
    price: "399.00",
    stock: 45,
    imageUrl: "https://picsum.photos/seed/smartwatch/400/400",
    category: "数码",
    status: "active",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "10",
    businessId: "P010",
    name: "创意生日礼物盲盒 惊喜拆箱",
    description: "精心搭配，每盒不同，给你惊喜",
    price: "79.00",
    stock: 200,
    imageUrl: "https://picsum.photos/seed/giftbox/400/400",
    category: "礼物",
    status: "active",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "11",
    businessId: "P011",
    name: "纯棉休闲短裤 夏季薄款",
    description: "弹力腰带，透气舒适，多色可选",
    price: "79.00",
    stock: 180,
    imageUrl: "https://picsum.photos/seed/shorts/400/400",
    category: "服饰",
    status: "active",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "12",
    businessId: "P012",
    name: "畅销小说精选套装 全5册",
    description: "豆瓣高分推荐，口碑之作",
    price: "118.00",
    stock: 90,
    imageUrl: "https://picsum.photos/seed/books/400/400",
    category: "图书",
    status: "active",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "13",
    businessId: "P013",
    name: "ins风香薰蜡烛 助眠安神",
    description: "天然植物蜡，持久留香，礼盒包装",
    price: "45.00",
    stock: 250,
    imageUrl: "https://picsum.photos/seed/candle/400/400",
    category: "家居",
    status: "active",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "14",
    businessId: "P014",
    name: "口红套装礼盒 6色哑光",
    description: "丝绒质地，持久不脱色，显白提气色",
    price: "158.00",
    stock: 100,
    imageUrl: "https://picsum.photos/seed/lipstick/400/400",
    category: "美妆",
    status: "active",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "15",
    businessId: "P015",
    name: "进口坚果大礼包 混合装1kg",
    description: "每日坚果，健康零食，新鲜直达",
    price: "88.00",
    stock: 350,
    imageUrl: "https://picsum.photos/seed/nuts/400/400",
    category: "美食",
    status: "active",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "16",
    businessId: "P016",
    name: "Type-C快充数据线 1.5米",
    description: "6A大电流，编织线材，耐弯折",
    price: "19.90",
    stock: 800,
    imageUrl: "https://picsum.photos/seed/cable/400/400",
    category: "数码",
    status: "active",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

export const MOCK_BANNERS = [
  {
    id: 1,
    title: "新品首发",
    subtitle: "限时优惠 低至5折",
    bg: "from-pink-500 to-rose-500",
    imageUrl: "https://picsum.photos/seed/banner1/800/400",
  },
  {
    id: 2,
    title: "品质好物",
    subtitle: "精选推荐 品质保证",
    bg: "from-blue-500 to-indigo-500",
    imageUrl: "https://picsum.photos/seed/banner2/800/400",
  },
  {
    id: 3,
    title: "超值特惠",
    subtitle: "每日上新 惊喜不断",
    bg: "from-orange-400 to-red-500",
    imageUrl: "https://picsum.photos/seed/banner3/800/400",
  },
];
